=== marianamf0/generator-scenario/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "startYear": {
            "type": "integer",
            "minimum": 2000,
            "maximum": 2029
        },
        "endYear": {
            "type": "integer",
            "minimum": 2000,
            "maximum": 2029
        },
        "age": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100
        },
        "email": {
            "type": "string",
            "format": "email"
        },
        "status": {
            "type": "string",
            "enum": [
                "active",
                "inactive"
            ]
        },
        "start_date": {
            "type": "string",
            "format": "date"
        },
        "data": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 1,
                "maximum": 100
            },
            "minItems": 3,
            "maxItems": 3
        },
        "data_2": {
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {
                "type": "array",
                "minItems": 4,
                "maxItems": 4,
                "items": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 100
                }
            }
        },
        "product": {
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 100
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ]
            }
        }
    },
    "required": [
        "age",
        "email",
        "status",
        "data",
        "product",
        "startYear",
        "endYear"
    ],
    "dependencies": {
        "start_date": [
            "status"
        ]
    }
}

=== marianamf0/generator-scenario/debug_data/scenario_11.json
{
    "startYear": 2007,
    "endYear": 2021,
    "age": 18,
    "email": "yangcrystal@example.com",
    "status": "inactive",
    "data": [
        7,
        94,
        81
    ],
    "product": [
        {
            "id": 86,
            "name": "foreign"
        },
        {
            "id": 30,
            "name": "ahead"
        },
        {
            "id": 84,
            "name": "serve"
        }
    ]
}

=== marianamf0/generator-scenario/debug_data/scenario_5.json
{
    "startYear": 2028,
    "endYear": 2027,
    "age": 55,
    "email": "yangcrystal@example.com",
    "status": "active",
    "data": [
        7,
        94,
        81
    ],
    "product": [
        {
            "id": 86,
            "name": "foreign"
        },
        {
            "id": 30,
            "name": "ahead"
        },
        {
            "id": 84,
            "name": "serve"
        }
    ]
}
